### ISSUE TITLE
finish formatting button on the index

### ISSUE THREAD

**Issue by chloejepson** [websys-group1/GNH#6]
the button on the index page is stuck on the bottom left, can someone try to move it up to the bottom right? above the annimation

**Comment by chloejepson** [comment]
don't forget to comment your work into the readme. Also, on the activities page, the text barely goes out of bounds to the right in the bottom corner, can someone help with that? thanks.

**Comment by LubnaIsmail** [comment]
Hey I took a look, to move the button can you put it in a div and then position it like text align to the right? If not I can research some different ways.
